language: node_js

node_js:
  - "iojs"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run travis
